/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shoeb-pc
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Category = new javax.swing.JMenuItem();
        Products = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        dealers = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        ad_entry = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        customer_search = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        employees_entry = new javax.swing.JMenuItem();
        jMenu20 = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        a_log_details = new javax.swing.JMenuItem();
        a_log_out = new javax.swing.JMenuItem();
        a_exit = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        jMenu8.setText("jMenu8");

        jMenu9.setText("jMenu9");

        jMenu10.setText("jMenu10");

        jMenu12.setText("jMenu12");

        jMenu13.setText("jMenu13");

        jMenu14.setText("jMenu14");

        jMenu16.setText("jMenu16");

        jMenu19.setText("jMenu19");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(845, 2147483647));
        setPreferredSize(new java.awt.Dimension(880, 485));
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("::: ADMIN HOME :::"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(910, 425));
        jLabel3.setMinimumSize(new java.awt.Dimension(910, 425));
        jLabel3.setPreferredSize(new java.awt.Dimension(910, 428));

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("Products Information");
        jMenu1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        Category.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Category.setText("New Brand Entry");
        Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryActionPerformed(evt);
            }
        });
        jMenu1.add(Category);

        Products.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        Products.setText("New Products Entry");
        Products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductsActionPerformed(evt);
            }
        });
        jMenu1.add(Products);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("      Dealers ");
        jMenu2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        dealers.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        dealers.setText("Add Dealers");
        dealers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealersActionPerformed(evt);
            }
        });
        jMenu2.add(dealers);

        jMenuBar1.add(jMenu2);

        jMenu15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu15.setText("    Admins ");
        jMenu15.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        ad_entry.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        ad_entry.setText("Admins Entry");
        ad_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad_entryActionPerformed(evt);
            }
        });
        jMenu15.add(ad_entry);

        jMenuBar1.add(jMenu15);

        jMenu3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setText("    Customers ");
        jMenu3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        customer_search.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        customer_search.setText("Customers Search");
        customer_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_searchActionPerformed(evt);
            }
        });
        jMenu3.add(customer_search);

        jMenuBar1.add(jMenu3);

        jMenu7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu7.setText("    Employees ");
        jMenu7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        employees_entry.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        employees_entry.setText("Employees Entry");
        employees_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employees_entryActionPerformed(evt);
            }
        });
        jMenu7.add(employees_entry);

        jMenuBar1.add(jMenu7);

        jMenu20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu20.setText("    Copyright ");
        jMenu20.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        about.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenu20.add(about);

        jMenuBar1.add(jMenu20);

        jMenu18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu18.setText("    Users ");
        jMenu18.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N

        a_log_details.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        a_log_details.setText("Change Password");
        a_log_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_log_detailsActionPerformed(evt);
            }
        });
        jMenu18.add(a_log_details);

        a_log_out.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        a_log_out.setText("Log Out");
        a_log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_log_outActionPerformed(evt);
            }
        });
        jMenu18.add(a_log_out);

        a_exit.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        a_exit.setText("Exit");
        a_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_exitActionPerformed(evt);
            }
        });
        jMenu18.add(a_exit);

        jMenuBar1.add(jMenu18);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(914, 914, 914)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(465, 465, 465))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryActionPerformed
        // TODO add your handling code here:
        Category aa = new Category();
        aa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CategoryActionPerformed

    private void a_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_a_exitActionPerformed

    private void a_log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_log_outActionPerformed
        // TODO add your handling code here:
        StartPage sp = new StartPage();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_a_log_outActionPerformed

    private void ProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductsActionPerformed
        // TODO add your handling code here:
        Products aa = new Products();
        aa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductsActionPerformed

    private void dealersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealersActionPerformed
        // TODO add your handling code here:
        DealerEntry aa = new DealerEntry();
        aa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dealersActionPerformed

    private void customer_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_searchActionPerformed
        // TODO add your handling code here:
        CustomersEntryRecord aa = new CustomersEntryRecord();
        aa.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_customer_searchActionPerformed

    private void employees_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employees_entryActionPerformed
        // TODO add your handling code here:
        EmployesEntry aa = new EmployesEntry();
        aa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_employees_entryActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        About aa = new About();
        aa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_aboutActionPerformed

    private void a_log_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_log_detailsActionPerformed
        // TODO add your handling code here:
        AdChangePassword aa = new AdChangePassword();
        aa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_a_log_detailsActionPerformed

    private void ad_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_entryActionPerformed
        // TODO add your handling code here:
        AdminEntry aa = new AdminEntry();
        aa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ad_entryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Category;
    private javax.swing.JMenuItem Products;
    private javax.swing.JMenuItem a_exit;
    private javax.swing.JMenuItem a_log_details;
    private javax.swing.JMenuItem a_log_out;
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem ad_entry;
    private javax.swing.JMenuItem customer_search;
    private javax.swing.JMenuItem dealers;
    private javax.swing.JMenuItem employees_entry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
