
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shoeb-pc
 */
public class Category extends javax.swing.JFrame {

    Connection connect = null;
    ResultSet rs;
    static String DatabaseName = "MOBILE_SHOP";
    public int flag = 0;
    
    /**
     * Creates new form CATEGORY
     */
    public Category() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        a_back_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        c_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        c_id = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        nk_new = new javax.swing.JButton();
        nk_save = new javax.swing.JButton();
        nk_update = new javax.swing.JButton();
        nk_delete = new javax.swing.JButton();
        nk_search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Brand Entry");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        a_back_button.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        a_back_button.setForeground(new java.awt.Color(0, 51, 51));
        a_back_button.setText("BACK");
        a_back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_back_buttonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Buxton Sketch", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/category.png"))); // NOI18N
        jLabel2.setText("Brand");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Brand Name : ");

        c_name.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Brand Id : ");

        c_id.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        c_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(c_name, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(c_id, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(c_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(c_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nk_new.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nk_new.setText("NEW");
        nk_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nk_newActionPerformed(evt);
            }
        });

        nk_save.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nk_save.setText("SAVE");
        nk_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nk_saveActionPerformed(evt);
            }
        });

        nk_update.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nk_update.setText("UPDATE");
        nk_update.setEnabled(false);
        nk_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nk_updateActionPerformed(evt);
            }
        });

        nk_delete.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nk_delete.setText("DELETE");
        nk_delete.setEnabled(false);
        nk_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nk_deleteActionPerformed(evt);
            }
        });

        nk_search.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nk_search.setText("VIEW BRANDS");
        nk_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nk_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nk_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nk_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nk_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nk_save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nk_new, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nk_new)
                .addGap(18, 18, 18)
                .addComponent(nk_save)
                .addGap(18, 18, 18)
                .addComponent(nk_update)
                .addGap(18, 18, 18)
                .addComponent(nk_delete)
                .addGap(18, 18, 18)
                .addComponent(nk_search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a_back_button, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(311, 311, 311))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(251, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(a_back_button)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(166, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(245, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a_back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_back_buttonActionPerformed
        // TODO add your handling code here:
        if(StartPage.LoginAs == 0)
        {
        AdminHome ah = new AdminHome();
        ah.setVisible(true);
        this.dispose();         
        }
        else if(StartPage.LoginAs == 1)
        {
        EmployeeHome eh = new EmployeeHome();
        eh.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_a_back_buttonActionPerformed

    private void nk_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nk_newActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_nk_newActionPerformed

    private void nk_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nk_saveActionPerformed
        // TODO add your handling code here:
        SaveNK();
    }//GEN-LAST:event_nk_saveActionPerformed

    private void nk_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nk_updateActionPerformed
        // TODO add your handling code here:
        UpdateNK();
    }//GEN-LAST:event_nk_updateActionPerformed

    private void nk_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nk_deleteActionPerformed
        // TODO add your handling code here:
        DeleteNK();
    }//GEN-LAST:event_nk_deleteActionPerformed

    private void nk_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nk_searchActionPerformed
        // TODO add your handling code here:
        CategoryRecord spr = new CategoryRecord();
        spr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nk_searchActionPerformed

    private void c_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Category().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a_back_button;
    public javax.swing.JTextField c_id;
    public javax.swing.JTextField c_name;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JButton nk_delete;
    public javax.swing.JButton nk_new;
    public javax.swing.JButton nk_save;
    public javax.swing.JButton nk_search;
    public javax.swing.JButton nk_update;
    // End of variables declaration//GEN-END:variables

    private void Reset() {
        flag = 0;
        c_name.setText("");
        c_id.setText("");
        nk_save.setEnabled(true);
        nk_update.setEnabled(false);
        nk_delete.setEnabled(false);
        c_id.setEditable(true);
        c_id.requestDefaultFocus();
    }

    private void SaveNK() {
        try{
             connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
             
           
            if (c_name.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Category Name","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (c_id.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Category ID","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
  
            
            String sql="Select CategoryId from CATEGORIES where CategoryId= '" + c_id.getText() + "'";
            connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
            rs= SQLServerConnect.SearchDB(connect, sql);
            
            if(rs.next()){
                JOptionPane.showMessageDialog( this, "Product ID already exists","Error", JOptionPane.ERROR_MESSAGE);
                c_id.setText("");
                c_id.requestDefaultFocus();
                return;
            }
            
            SQLServerConnect.Close(connect);
            
            sql= "insert into CATEGORIES(CategoryId, CategoryName)values('"+ c_id.getText() + "','"+ c_name.getText() + "')";
            
            connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
            SQLServerConnect.UpdateDB(connect, sql);
            SQLServerConnect.Close(connect);
            JOptionPane.showMessageDialog(this,"Successfully saved","Record",JOptionPane.INFORMATION_MESSAGE);
            nk_save.setEnabled(false);
            Reset();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this,e);        
        }
    }

    private void UpdateNK() {
        try{
        connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
        //String sql= "update nokia_entry set type='"+ nk_combo.getSelectedItem() + "',model='"+ nk_model.getText()+ "',id='"+ nk_id.getText()+ "',colour='"+ nk_colour.getText()+ "',stock='"+ nk_stock.getText() + "' where price='"+ nk_price.getText() + "'";
        //String sql= "'"+ nk_combo.getSelectedItem() + "','"+ nk_model.getText() + "','"+ nk_id.getText()+ "','"+ nk_colour.getText() + "','"+ nk_stock.getText()+ "','"+ nk_price.getText()+ "'";
        String sql= "update CATEGORIES set CategoryName='"+ c_name.getText()+ "' where CategoryId='"+ c_id.getText() + "'";
        SQLServerConnect.UpdateDB(connect, sql);
        JOptionPane.showMessageDialog(this,"Successfully updated","Record",JOptionPane.INFORMATION_MESSAGE);
        nk_update.setEnabled(false);
        Reset();
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(this,e);
        }
    }

    private void DeleteNK() {
        try{
            int sure = JOptionPane.showConfirmDialog(null," Are you sure want to delete ?","Confirmation",JOptionPane.YES_NO_OPTION);

            if(sure == 0){
                connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
                String sql = "delete from CATEGORIES where CategoryId = '" + c_id.getText() + "'";
                SQLServerConnect.UpdateDB(connect, sql);
                
                boolean success1 = SQLServerConnect.UpdateDB(connect, sql);

                if(!success1){
                    JOptionPane.showMessageDialog(this,"Couldn't Delete. Try Again","Record",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Successfully deleted","Record",JOptionPane.INFORMATION_MESSAGE);
                    Reset();
                }
            }

        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(this,e);
        }
    }
}
