
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shoeb-pc
 */
public class CustomersEntry extends javax.swing.JFrame {

    Connection connect = null;
    ResultSet rs;
    static String DatabaseName = "MOBILE_SHOP";
    public int flag = 0;
    
    /**
     * Creates new form CustomersEntry
     */
    public CustomersEntry() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        a_back_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cust_contact_number = new javax.swing.JTextField();
        cust_id = new javax.swing.JTextField();
        cust_name = new javax.swing.JTextField();
        cust_address = new javax.swing.JTextField();
        cust_gender_combo = new javax.swing.JComboBox();
        cust_type_combo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cust_since = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cust_entry_new = new javax.swing.JButton();
        cust_entry_save = new javax.swing.JButton();
        cust_entry_update = new javax.swing.JButton();
        cust_entry_delete = new javax.swing.JButton();
        cust_entry_search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("||| CUSTOMER ENTRY |||");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        a_back_button.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        a_back_button.setForeground(new java.awt.Color(0, 51, 51));
        a_back_button.setText("BACK");
        a_back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_back_buttonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Buxton Sketch", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cust logo.jpg"))); // NOI18N
        jLabel1.setText("CUSTOMER ENTRY ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("ID :");

        jLabel3.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Name :");

        jLabel4.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Type :");

        jLabel5.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Gender :");

        jLabel6.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Contact Number :");

        jLabel8.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Address :");

        cust_contact_number.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N

        cust_id.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N

        cust_name.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N

        cust_address.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N

        cust_gender_combo.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        cust_gender_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        cust_gender_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_gender_comboActionPerformed(evt);
            }
        });

        cust_type_combo.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        cust_type_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RETAIL", "WHOLESALE"}));

        jLabel9.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Customer Since :");

        cust_since.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cust_id, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cust_contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cust_address, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cust_since, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cust_type_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cust_name)
                            .addComponent(cust_gender_combo, 0, 323, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cust_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cust_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cust_gender_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cust_type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cust_contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addComponent(cust_address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cust_since, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cust_entry_new.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cust_entry_new.setText("NEW");
        cust_entry_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_entry_newActionPerformed(evt);
            }
        });

        cust_entry_save.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cust_entry_save.setText("SAVE");
        cust_entry_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_entry_saveActionPerformed(evt);
            }
        });

        cust_entry_update.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cust_entry_update.setText("UPDATE");
        cust_entry_update.setEnabled(false);
        cust_entry_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_entry_updateActionPerformed(evt);
            }
        });

        cust_entry_delete.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cust_entry_delete.setText("DELETE");
        cust_entry_delete.setEnabled(false);
        cust_entry_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_entry_deleteActionPerformed(evt);
            }
        });

        cust_entry_search.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cust_entry_search.setText("SEARCH");
        cust_entry_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_entry_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cust_entry_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cust_entry_new, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cust_entry_save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cust_entry_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cust_entry_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cust_entry_new)
                .addGap(18, 18, 18)
                .addComponent(cust_entry_save)
                .addGap(18, 18, 18)
                .addComponent(cust_entry_update)
                .addGap(18, 18, 18)
                .addComponent(cust_entry_delete)
                .addGap(18, 18, 18)
                .addComponent(cust_entry_search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(a_back_button)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(207, 207, 207)
                    .addComponent(jLabel1)
                    .addContainerGap(275, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(a_back_button)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jLabel1)
                    .addContainerGap(534, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a_back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_back_buttonActionPerformed
        // TODO add your handling code here:
       if(StartPage.LoginAs == 0)
        {
        AdminHome ah = new AdminHome();
        ah.setVisible(true);
        this.dispose();         
        }
        else if(StartPage.LoginAs == 1)
        {
        EmployeeHome eh = new EmployeeHome();
        eh.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_a_back_buttonActionPerformed

    private void cust_entry_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_entry_updateActionPerformed
        // TODO add your handling code here:
        UpdatecCE();
    }//GEN-LAST:event_cust_entry_updateActionPerformed

    private void cust_entry_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_entry_newActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_cust_entry_newActionPerformed

    private void cust_entry_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_entry_saveActionPerformed
        // TODO add your handling code here:
        Savece();
    }//GEN-LAST:event_cust_entry_saveActionPerformed

    private void cust_gender_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_gender_comboActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_cust_gender_comboActionPerformed

    private void cust_entry_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_entry_searchActionPerformed
        // TODO add your handling code here:
        CustomersEntryRecord cer= new CustomersEntryRecord();
        cer.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cust_entry_searchActionPerformed

    private void cust_entry_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_entry_deleteActionPerformed
        // TODO add your handling code here:
        DeleteCE();
    }//GEN-LAST:event_cust_entry_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomersEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomersEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomersEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomersEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomersEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a_back_button;
    public javax.swing.JTextField cust_address;
    public javax.swing.JTextField cust_contact_number;
    public javax.swing.JButton cust_entry_delete;
    public javax.swing.JButton cust_entry_new;
    public javax.swing.JButton cust_entry_save;
    public javax.swing.JButton cust_entry_search;
    public javax.swing.JButton cust_entry_update;
    public javax.swing.JComboBox cust_gender_combo;
    public javax.swing.JTextField cust_id;
    public javax.swing.JTextField cust_name;
    public javax.swing.JTextField cust_since;
    public javax.swing.JComboBox cust_type_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    private void Reset() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    
        flag = 0;
        cust_id.setText("");
        cust_name.setText("");
        cust_gender_combo.setSelectedIndex(-1);
        cust_since.setText("");
        cust_type_combo.setSelectedIndex(-1);
        cust_contact_number.setText("");
        cust_address.setText("");
        
        cust_entry_save.setEnabled(true);
        cust_entry_update.setEnabled(false);
        cust_entry_delete.setEnabled(false);
        cust_id.setEditable(true);
        cust_id.requestDefaultFocus();
        
    }

    private void UpdatecCE() {
        try{
        connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
        
        String sql= "update CUSTOMERS set CustomerName='"+ cust_name.getText() + "',Gender='"+ cust_gender_combo.getSelectedItem()+ "',CustomerSince='"+ cust_since.getText() + "',CustomerType='" + cust_type_combo.getSelectedItem() + "',CustomerPhone='" + cust_contact_number.getText() + "',CustomerAddress='"+ cust_address.getText() + "' where CustomerId='"+ cust_id.getText() + "'";
        SQLServerConnect.UpdateDB(connect, sql);
        JOptionPane.showMessageDialog(this,"Successfully updated","Record",JOptionPane.INFORMATION_MESSAGE);
        cust_entry_update.setEnabled(false);
        Reset();
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(this,e);
        }
    }

    private void Savece() {
        try{
             connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
             
             if (cust_id.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Customer ID","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (cust_name.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Customer Name","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (cust_gender_combo.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog( this, "Please select Gender","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (cust_since.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Customer Since" ,"Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (cust_type_combo.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog( this, "Please select Customer Type","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }         
           
            if (cust_contact_number.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Contact Number","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }                 
            
            if (cust_address.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter address","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
             
            String sql="Select CustomerId from CUSTOMERS where CustomerId= '" + cust_id.getText() + "'";
            connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
            rs= SQLServerConnect.SearchDB(connect, sql);
            
            if(rs.next()){
                JOptionPane.showMessageDialog( this, "id already exists","Error", JOptionPane.ERROR_MESSAGE);
                cust_id.setText("");
                cust_id.requestDefaultFocus();
                return;
            }
            
            SQLServerConnect.Close(connect);
            
            sql= "insert into CUSTOMERS(CustomerId,CustomerName,Gender,CustomerSince,CustomerType,CustomerPhone,CustomerAddress)values('"+ cust_id.getText() + "','"+ cust_name.getText() + "','"+ cust_gender_combo.getSelectedItem()+ "','"+ cust_since.getText() + "','"+ cust_type_combo.getSelectedItem()+ "','" + cust_contact_number.getText() + "','"+ cust_address.getText() + "')";
            
            connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
            SQLServerConnect.UpdateDB(connect, sql);
            SQLServerConnect.Close(connect);
            JOptionPane.showMessageDialog(this,"Successfully saved !!!","Record",JOptionPane.INFORMATION_MESSAGE);
            cust_entry_save.setEnabled(false);
            Reset();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this,e);        
        }
        
    }

    private void DeleteCE() {
        try{
            int sure = JOptionPane.showConfirmDialog(null," Are you sure want to delete ?","Confirmation",JOptionPane.YES_NO_OPTION);

            if(sure == 0){
                connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
                String sql = "delete from CUSTOMERS where CustomerId = '" + cust_id.getText() + "'";
                SQLServerConnect.UpdateDB(connect, sql);
                
                boolean success1 = SQLServerConnect.UpdateDB(connect, sql);

                if(!success1){
                    JOptionPane.showMessageDialog(this,"Couldn't Delete. Try Again","Record",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Successfully deleted","Record",JOptionPane.INFORMATION_MESSAGE);
                    Reset();
                }
            }

        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(this,e);
        }
    }
}
