
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shoeb-pc
 */
public class DealerEntry extends javax.swing.JFrame {

    Connection connect = null;
    ResultSet rs;
    static String DatabaseName = "MOBILE_SHOP";
    public int flag = 0;
    
    /**
     * Creates new form HeadPhones
     */
    public DealerEntry() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        a_back_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        d_name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        d_address = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        d_phone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        d_id = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        d_product = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        hd_new = new javax.swing.JButton();
        hd_save = new javax.swing.JButton();
        hd_update = new javax.swing.JButton();
        hd_delete = new javax.swing.JButton();
        hd_search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("||| Dealers Entry |||");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        a_back_button.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        a_back_button.setForeground(new java.awt.Color(0, 51, 51));
        a_back_button.setText("BACK");
        a_back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_back_buttonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Buxton Sketch", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dealer.jpg"))); // NOI18N
        jLabel2.setText("Dealer Entry");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Dealer Name : ");

        d_name.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Address : ");

        d_address.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Phone : ");

        d_phone.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        d_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_phoneActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Dealer Id : ");

        d_id.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("Product Id : ");

        d_product.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        d_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_productActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(d_product, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(d_name, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addComponent(d_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                        .addComponent(d_address)
                        .addComponent(d_id)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(d_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(d_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(d_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(d_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(d_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        hd_new.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        hd_new.setText("NEW");
        hd_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hd_newActionPerformed(evt);
            }
        });

        hd_save.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        hd_save.setText("SAVE");
        hd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hd_saveActionPerformed(evt);
            }
        });

        hd_update.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        hd_update.setText("UPDATE");
        hd_update.setEnabled(false);
        hd_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hd_updateActionPerformed(evt);
            }
        });

        hd_delete.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        hd_delete.setText("DELETE");
        hd_delete.setEnabled(false);
        hd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hd_deleteActionPerformed(evt);
            }
        });

        hd_search.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        hd_search.setText("SEARCH");
        hd_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hd_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hd_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hd_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hd_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hd_save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hd_new, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hd_new)
                .addGap(18, 18, 18)
                .addComponent(hd_save)
                .addGap(18, 18, 18)
                .addComponent(hd_update)
                .addGap(18, 18, 18)
                .addComponent(hd_delete)
                .addGap(18, 18, 18)
                .addComponent(hd_search)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a_back_button, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 179, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(246, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(66, 66, 66)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(a_back_button)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(143, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(84, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a_back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_back_buttonActionPerformed
        // TODO add your handling code here:
        if(StartPage.LoginAs == 0)
        {
        AdminHome ah = new AdminHome();
        ah.setVisible(true);
        this.dispose();         
        }
        else if(StartPage.LoginAs == 1)
        {
        EmployeeHome eh = new EmployeeHome();
        eh.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_a_back_buttonActionPerformed

    private void d_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_phoneActionPerformed

    private void hd_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hd_newActionPerformed
        // TODO add your handling code here:
        Reset();
    }//GEN-LAST:event_hd_newActionPerformed

    private void hd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hd_saveActionPerformed
        // TODO add your handling code here:
        SaveHD();
    }//GEN-LAST:event_hd_saveActionPerformed

    private void hd_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hd_updateActionPerformed
        // TODO add your handling code here:
        UpdateHD();
    }//GEN-LAST:event_hd_updateActionPerformed

    private void hd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hd_deleteActionPerformed
        // TODO add your handling code here:
        DeleteHD();
    }//GEN-LAST:event_hd_deleteActionPerformed

    private void hd_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hd_searchActionPerformed
        // TODO add your handling code here:
        DealerRecord spr = new DealerRecord();
        spr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hd_searchActionPerformed

    private void d_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_productActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DealerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DealerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DealerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DealerEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DealerEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a_back_button;
    public javax.swing.JTextField d_address;
    public javax.swing.JTextField d_id;
    public javax.swing.JTextField d_name;
    public javax.swing.JTextField d_phone;
    public javax.swing.JTextField d_product;
    public javax.swing.JButton hd_delete;
    public javax.swing.JButton hd_new;
    public javax.swing.JButton hd_save;
    public javax.swing.JButton hd_search;
    public javax.swing.JButton hd_update;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private void Reset() {
        flag = 0;
        d_name.setText("");
        d_id.setText("");
        d_address.setText("");
        d_phone.setText("");
        hd_save.setEnabled(true);
        hd_update.setEnabled(false);
        hd_delete.setEnabled(false);
        d_id.setEditable(true);
        d_id.requestDefaultFocus();
    }

    private void SaveHD() {
        try{
             connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
             
            
            if (d_name.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Dealer Name","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (d_id.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Dealer ID","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (d_address.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Dealer Address","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (d_phone.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Dealer Phone","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (d_product.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter Product Id","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            
            String sql="Select DealerId from DEALERS where DealerId= '" + d_id.getText() + "'";
            connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
            rs= SQLServerConnect.SearchDB(connect, sql);
            
            if(rs.next()){
                JOptionPane.showMessageDialog( this, "Product ID already exists","Error", JOptionPane.ERROR_MESSAGE);
                d_id.setText("");
                d_id.requestDefaultFocus();
                return;
            }
            
            SQLServerConnect.Close(connect);
            
            sql= "insert into DEALERS(DealerId, DealerName, DealerAddress, DealerPhone, ProductId)values('"+ d_id.getText() + "','"+ d_name.getText()+ "','"+ d_address.getText() + "','"+ d_phone.getText()+ "','"+ d_product.getText()+ "')";
            
            connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
            SQLServerConnect.UpdateDB(connect, sql);
            SQLServerConnect.Close(connect);
            JOptionPane.showMessageDialog(this,"Successfully saved","Record",JOptionPane.INFORMATION_MESSAGE);
            hd_save.setEnabled(false);
            Reset();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this,e);        
        }
    }

    private void UpdateHD() {
        try{
        connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
        String sql= "update DEALERS set DealerName='"+ d_name.getText() + "',DealerAddress='"+ d_address.getText() + "',DealerPhone='"+ d_phone.getText()+ "',ProductId='"+ d_product.getText()+ "' where DealerId='"+ d_id.getText()+ "'";
        SQLServerConnect.UpdateDB(connect, sql);
        JOptionPane.showMessageDialog(this,"Successfully updated","Record",JOptionPane.INFORMATION_MESSAGE);
        hd_update.setEnabled(false);
        Reset();
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(this,e);
        }
    }

    private void DeleteHD() {
        try{
            int sure = JOptionPane.showConfirmDialog(null," Are you sure want to delete ?","Confirmation",JOptionPane.YES_NO_OPTION);

            if(sure == 0){
                connect = SQLServerConnect.ConnectDB("sa", "123456789", "MOBILE_SHOP");
                String sql = "delete from DEALERS where DealerId = '" + d_id.getText() + "'";
                SQLServerConnect.UpdateDB(connect, sql);
                
                boolean success1 = SQLServerConnect.UpdateDB(connect, sql);

                if(!success1){
                    JOptionPane.showMessageDialog(this,"Couldn't Delete. Try Again","Record",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Successfully deleted","Record",JOptionPane.INFORMATION_MESSAGE);
                    Reset();
                }
            }

        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(this,e);
        }
    }
}
